version: '3.8'

services:
  oracle:
    image: gvenzl/oracle-free
    container_name: "oracle"
    environment:
      ORACLE_PDB_NAME: FREEPDB1
      ORACLE_USER: system
      ORACLE_PASSWORD: SysPassword1
    ports:
      - "1521:1521"

  spring-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: "employee_management"
    ports:
      - "8080:8080"
    depends_on:
      - oracle
    environment:
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@//oracle:1521/FREEPDB1
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: SysPassword1
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: oracle.jdbc.OracleDriver
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
      SERVER_PORT: 8080
      SPRING_SERVLET_CONTEXT_PATH: /api
      SPRINGDOC_API_DOCS_PATH: /api-docs
      SPRINGDOC_SWAGGER_UI_PATH: /swagger-ui.html
